apiVersion: apps/v1
kind: Deployment
metadata:
  name: malie-deployment
  labels:
    app: my-malie
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-malie
  template:
    metadata:
      labels:
        app: my-malie
    spec:
      containers:
      - name: my-image
        image: malie480/intelus:latest
        ports:
        - containerPort: 8080
